[tool.black]
line_length = 94

[tool.isort]
profile = "black"
known_third_party = ["vivarium", "vivarium_public_health"]

[tool.coverage.run]
source = ["vivarium_gates_nutrition_optimization_child"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
testpaths = ["tests/"]